# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazycron < Formula
  desc "A lazy TUI for managing cron jobs"
  homepage "https://github.com/swalha1999/lazycron"
  version "0.11.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/swalha1999/lazycron/releases/download/v0.11.4/lazycron_0.11.4_darwin_amd64.tar.gz"
      sha256 "5836f9e1a1e4393cdca1eeac19964de5956e443c3dd7e7f4bbd0d8a594145534"

      define_method(:install) do
        bin.install "lazycron"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/swalha1999/lazycron/releases/download/v0.11.4/lazycron_0.11.4_darwin_arm64.tar.gz"
      sha256 "9a436ec862b2888777799302acbb8ecb1b5c724acb49e9a5568ac8f3aaa508ac"

      define_method(:install) do
        bin.install "lazycron"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/swalha1999/lazycron/releases/download/v0.11.4/lazycron_0.11.4_linux_amd64.tar.gz"
      sha256 "2e7f4b1f4e5687bb10f9a17a8fabbcec0c97a05cbd9ac3e883c69079888beaaa"
      define_method(:install) do
        bin.install "lazycron"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/swalha1999/lazycron/releases/download/v0.11.4/lazycron_0.11.4_linux_arm64.tar.gz"
      sha256 "fe51acb250c6bc13a327d5f6bd2784bf95bccfdcecd78dc69fb759398a96af64"
      define_method(:install) do
        bin.install "lazycron"
      end
    end
  end
end
