# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazycron < Formula
  desc "A lazy TUI for managing cron jobs"
  homepage "https://github.com/swalha1999/lazycron"
  version "0.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/swalha1999/lazycron/releases/download/v0.4.1/lazycron_0.4.1_darwin_amd64.tar.gz"
      sha256 "348797b96e723e3412c07ed5f669aa9197c977197ccc4ec2721d2de2f0e98fab"

      define_method(:install) do
        bin.install "lazycron"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/swalha1999/lazycron/releases/download/v0.4.1/lazycron_0.4.1_darwin_arm64.tar.gz"
      sha256 "0caa2eae55b6aaead0491528ca73912447aa5825e9c87ae5648f2636d4affdcc"

      define_method(:install) do
        bin.install "lazycron"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/swalha1999/lazycron/releases/download/v0.4.1/lazycron_0.4.1_linux_amd64.tar.gz"
      sha256 "5e7a9d75b0eb09cef1da9c39dd951dcc9d8874ff1119be6ff8cf68ed1a0be92b"
      define_method(:install) do
        bin.install "lazycron"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/swalha1999/lazycron/releases/download/v0.4.1/lazycron_0.4.1_linux_arm64.tar.gz"
      sha256 "9dd23dc7898ba69fa5b7768c8da69a909f59d148ba303b66ddb623a46d15fee2"
      define_method(:install) do
        bin.install "lazycron"
      end
    end
  end
end
