# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazycron < Formula
  desc "A lazy TUI for managing cron jobs"
  homepage "https://github.com/swalha1999/lazycron"
  version "0.9.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/swalha1999/lazycron/releases/download/v0.9.0/lazycron_0.9.0_darwin_amd64.tar.gz"
      sha256 "45d4f8d1f656a6b22aa9243f22d738cd13b108ea8aad40e7a7b497aeec9dfe35"

      define_method(:install) do
        bin.install "lazycron"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/swalha1999/lazycron/releases/download/v0.9.0/lazycron_0.9.0_darwin_arm64.tar.gz"
      sha256 "ee6bc9fb0f1186e38d551b318129b7ea7e29e2ae087829ce337561c8ebbff1b7"

      define_method(:install) do
        bin.install "lazycron"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/swalha1999/lazycron/releases/download/v0.9.0/lazycron_0.9.0_linux_amd64.tar.gz"
      sha256 "b02a403bdb3707cde2cee5935a0f6937205bbb254b673d239d8d63da0bed8208"
      define_method(:install) do
        bin.install "lazycron"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/swalha1999/lazycron/releases/download/v0.9.0/lazycron_0.9.0_linux_arm64.tar.gz"
      sha256 "9a4be504f43eb90238ea44c373425e781070865704ce2d84662bf5023feddc5d"
      define_method(:install) do
        bin.install "lazycron"
      end
    end
  end
end
